from enum import StrEnum

class Platform(StrEnum):
    _4CHAN = '4chan'
    _8KUN = '8kun'
    BLUESKY = 'bluesky'
    BITCHUTE = 'bitchute_comment'
    FEDIVERSE = 'fediverse'
    GAB = 'gab'
    GETTR = 'gettr'
    KIWIFARMS = 'kiwifarms'
    LBRY = 'lbry_comment'
    MEWE = 'mewe'
    MINDS = 'minds'
    OK = 'ok'
    PARLER = 'parler'
    POAL = 'poal'
    RUMBLE = 'rumble_comment'
    RUTUBE = 'rutube_comment'
    WIN = 'win'
    TELEGRAM = 'telegram'
    TIKTOK = 'tiktok_comment'
    TRUTH = 'truth_social'
    VK = 'vk'
    WIMKIN = 'wimkin'